### ISSUE TITLE
Please make sure it's a valid pdf file and try again

### ISSUE THREAD

**Issue by Yoloabdo** [Fueled/ios-icon-generator#10]
I had this issue while trying to use it 

```identify: FailedToExecuteCommand `'gs' -sstdout=%stderr -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 '-sDEVICE=pngalpha' -dTextAlphaBits=4 -dGraphicsAlphaBits=4 '-r72x72'  '-sOutputFile=/var/folders/32/sdrnz_7x0bx0vj2wjgzzs8hw0000gn/T/magick-69608UJu90ZR4pNVx%d' '-f/var/folders/32/sdrnz_7x0bx0vj2wjgzzs8hw0000gn/T/magick-69608QZ4tIJm4qftV' '-f/var/folders/32/sdrnz_7x0bx0vj2wjgzzs8hw0000gn/T/magick-69608twKhWRGCUags'' (1) @ error/pdf.c/InvokePDFDelegate/290.
ERROR: Unable to verify icon. Please make sure it's a valid pdf file and try again.```

**Comment by stephanecopin** [comment]
Hi @Yoloabdo, there is one additional requirement that we forgot to mention, you just need to install GhostScript via homebrew:
```
brew install ghostscript
```
And then the tool should work as expected.

I'll create a PR that add this requirement both in the tool and in the readme, and publish an updated version.
